name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3   # pick your preferred version
          virtualenvs-create: true
          virtualenvs-in-project: true

      # 4. Install dependencies with Poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      # 5. Run tests
      - name: Run pytest
        run: poetry run pytest -v